spring:
  datasource:
    password: "geekrabit"
    url: jdbc:mysql://localhost:3306/PrepMate?allowPublicKeyRetrieval=true&useSSL=false
    username: geekrabit
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
jwt:
  secret: "PrepMateAISecretKey"
  expiration-time: 3600000
